# Generated by Django 2.1.4 on 2019-05-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('number', "Nombre de personne d'accord"), ('boolean', 'Consensus ou non')], max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('participants', models.PositiveIntegerField(verbose_name='Nombre de personne dans le groupe')),
                ('choice', models.PositiveIntegerField(verbose_name='Réponse')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Quelles sont vos propositions ?')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_visu.Group')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_visu.Question')),
            ],
        ),
    ]
