# Generated by Django 2.1.4 on 2018-12-07 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[("number", "Nombre "), ("boolean", "Oui ou non")],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table_visu.Question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "numero",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name="reponse",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="table_visu.Table"
            ),
        ),
    ]
