# Generated by Django 2.1.4 on 2018-12-07 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("table_visu", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="reponse",
            name="choice",
            field=models.IntegerField(default=0, verbose_name="Réponse"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reponse",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
