# Generated by Django 2.1.4 on 2018-12-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("table_visu", "0002_auto_20181207_1145")]

    operations = [
        migrations.AddField(
            model_name="reponse",
            name="participants",
            field=models.IntegerField(
                default=0, verbose_name="Nombre de personne dans le groupe"
            ),
            preserve_default=False,
        )
    ]
