# Generated by Django 2.1.4 on 2018-12-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("table_visu", "0003_reponse_participants")]

    operations = [
        migrations.AddField(
            model_name="reponse",
            name="comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Avez-vous d'autres propositions ?"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("number", "Nombre de personne d'accord"),
                    ("boolean", "Consensus ou non"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="reponse",
            name="choice",
            field=models.PositiveIntegerField(verbose_name="Réponse"),
        ),
        migrations.AlterField(
            model_name="reponse",
            name="participants",
            field=models.PositiveIntegerField(
                verbose_name="Nombre de personne dans le groupe"
            ),
        ),
    ]
