# Generated by Django 2.1.4 on 2018-12-08 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("table_visu", "0004_auto_20181208_1200")]

    operations = [
        migrations.AddField(
            model_name="question",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        )
    ]
