# Generated by Django 2.1.4 on 2018-12-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("table_visu", "0005_question_created")]

    operations = [
        migrations.AlterField(
            model_name="reponse",
            name="comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Quelles sont vos propositions ?"
            ),
        )
    ]
